### PR TITLE
Re-add .gitattributes and .gitignore files

### PR DESCRIPTION
**Pull request by insomniacUNDERSCORElemon**

### CODE REVIEW

**Comment by panno8M** [comment]
My lack of communication caused unnecessary hassle. Sorry about that.

**Comment by insomniacUNDERSCORElemon** [comment]
> My lack of communication caused unnecessary hassle. Sorry about that.

It's fine, I know I'm not the best/fastest at this (though as I've said for this particular issue I have those files they just didn't get uploaded).

Although I just noticed that you didn't do the .gitignores quite right. There's no lib folder at the project root, there are in core (and for decbinhex, also in movement_demo).

**Comment by panno8M** [comment]
I've unified all .gitignore into project root's one.

**Comment by insomniacUNDERSCORElemon** [comment]
Oh, ok.

**Pull request closed without merging**
