### PR TITLE
Refactor directory structure

### PR DESCRIPTION
**Pull request by panno8M**

### CODE REVIEW

**Comment by insomniacUNDERSCORElemon** [comment]
Should I be making these changes to my own demo project?

Also:

- currently the template .nimble still has the old `requires`
- have you considered re-naming the organization too, while it's early on?

**Comment by panno8M** [comment]
> Should I be making these changes to my own demo project?

If you plan to contribute to godot-nim/demo, by all means.

> currently the template .nimble still has the old requires

Correction omission. Thank you.

> have you considered re-naming the organization too, while it's early on?

I'm not going to change the name of the organization.
It is positioned as a gdext project, out of the plan to integrate godot and nim.

EDIT:
It's also because other language bindings use this format, so it's familiar. godot-cpp, godot-rust, and so on.

**Comment by insomniacUNDERSCORElemon** [comment]
> It is positioned as a gdext project, out of the plan to integrate godot and nim.
> EDIT:
It's also because other language bindings use this format, so it's familiar. godot-cpp, godot-rust, and so on.

I mention it because Godot-nim is the exact name of the 3.X bindings. As said before, even just adding a 4 in there somewhere would make it clearer.

------------------

Also forgot to say earlier (it's not really relevant to this other than being the demo repo): any thoughts on allowing push access? ~~A demo repo seems like the only place  where it makes sense (at least in the case of uploading an entirely new folder in a designated location).~~ 

~~Though I don't know how viable/safe it actually is, especially since it's usually turned off.~~

EDIT: Actually I see the issue with that now, I was just thinking it would allow a PR without forking the repo beforehand.

**Comment by panno8M** [comment]
> I mention it because Godot-nim is the exact name of the 3.X bindings. As said before, even just adding a 4 in there somewhere would make it clearer.

How about now? I only changed the display name.

**Comment by panno8M** [comment]
> Also forgot to say earlier (it's not really relevant to this other than being the demo repo): any thoughts on allowing push access?

It may be okay to allow against organization members.

**Comment by insomniacUNDERSCORElemon** [comment]
> How about now? I only changed the display name.

I was thinking more about searching and sharing. I can't see myself saying "made with Godot-Nim" _again_ without some awkward clarification.

**Comment by panno8M** [comment]
I generally agree, but I don't really want to put godot4 in the organization's name.
Let's say godot5 is released and this organization is still maintained until then. If that happens, I am sure we would want to change the name again. And that too with an organization that has grown large enough. This would go against the premise you conveyed.

If we change our name, I would prefer one that does not use a version number.

**Pull request merged**
