### PR TITLE
Corresponding #17

### LINKED ISSUE #17: Update demos to conform to the new directory structure
related to godot-nim/gdextshell#32

It also serves as a test for the `gdextwiz new-workspace` command.

### PR DESCRIPTION
**Pull request by panno8M**
@insomniacUNDERSCORElemon 
Is there anything in this configuration that we haven't addressed?

This configuration should be uniform only within the demo and should not be forced on the user, but would be a template for.

### CODE REVIEW

**Comment by insomniacUNDERSCORElemon** [comment]
Honestly I'm not sure why you structured it like that, but I guess as long as it compiles it's your demo. 

I'd guess it's something about including the `.nimble` file for publishing it as it would be a good first publish, but if you're going that route you might as well have kept the old structure.

On configuration, I think I still want it to be more streamlined but I guess it doesn't matter too much especially early on.

**Comment by panno8M** [comment]
The changes and their intent are described below.
It seems to have more flexibility in configuration than the bootstrap style.

* All restrictions on naming conventions, directory structure, etc. have been removed.
* Different build options can easily coexist by emptying the contents of config.nims and transferring them to nim.cfg or $extension.nim.cfg.
* By completely separating the library and class definitions from the extension's entry file (extensions/*.nim), the entry file itself functions as the workspace.

**Comment by panno8M** [comment]
The class library is still in the nimble package as before, but this is not forced on the user. I expect normal users to just list .nim directly under nim/.

**Comment by insomniacUNDERSCORElemon** [comment]
I didn't mean for one of my previous comments to be a challenge (I even admitted it wasn't important, likely future problems, and I shouldn't worry about it), and I can certainly live with it if just renaming the library is possible. 

This isn't what I had in mind for #32, I meant more like my PR for a new template. EDIT: And again, the creeps demo can be a normal addon, as I said

 > Particularly as the number of demos increases and as add-on structure changes for nimble publishing.

I mean more structures are fine but aside from not quite understanding it, seems to me like something like this should be used for a new project that can demonstrate the purpose. Particularly if you don't have a normal addon yet. I absolutely could be wrong though, seeing it only at surface-level.

**Review by insomniacUNDERSCORElemon — APPROVED** [review]
It works.

**Pull request closed without merging**
