### PR TITLE
Decbinhex code rework 2

### PR DESCRIPTION
**Pull request by insomniacUNDERSCORElemon**
I think this should cover everything. Most of the improvement is to the main class.

### CODE REVIEW

**Comment by panno8M** [comment]
Thank you very much.

There are a few areas for improvement, but they are minor and you may ignore them.

* Use std/ for importing standard libraries
* Use nimpretty for formatting. (You should be able to use the CLI or the editor extension's formatting command.)

**Comment by insomniacUNDERSCORElemon** [comment]
Any comments on functionality? I think I covered most cases (that I can) but it's always possible I missed something obvious.

I was hoping for a better way (multiple values, overlapping conditions) to use the case statement than I did, but it seems like that isn't possible. I saw mention of it working with sets, but I didn't see that usage.

EDIT: I guess maybe it'd defeat the point, and I'd just like if statements that supported ranges in a non-ugly way. I think I could come improve the structure more (perhaps using `block`), but it's probably good enough.

**Comment by panno8M** [comment]
It sounded interesting, so I tried writing one myself, but it turned out to be something completely different. I hope it will be of some help.

```nim
import std/[strutils, strformat]
import gdext
import gdextgen/classes/[gdSceneTree, gdInput, gdLineEdit, gdLabel, gdBaseButton]
import gdextgen/classes/gdWindow

type
  Base {.pure.} = enum
    Bin, Dec, Hex
  State = object
    input: string
    select: Base = Dec

  MainClass* = ref object of Control
    window: Window
    in_node: LineEdit
    out_node: Label
    bases: array[Base, BaseButton]
    state: State

func or0(str: string): string {.raises: [].} =
  if str.isEmptyOrWhiteSpace: "0"
  else: str

func removeExtra0(str: string): string {.raises: [].} =
  str.strip(trailing = false, chars = {'0'})

proc myToBin(value: int): string {.raises: [].} =
  try:
    "0b" & value.toBin(63).removeExtra0.or0.insertSep(' ', 4)
  except:
    getCurrentExceptionMsg()

proc myToHex(value: int): string {.raises: [].} =
  try:
    "0x" & value.toHex.removeExtra0.or0
  except:
    getCurrentExceptionMsg()

proc myToDec(value: int): string {.raises: [].} =
  "0d" & $value

proc output(self: MainClass; text: string) =
  self.out_node.text = text

method ready(self: MainClass) {.gdsync.} =
  if isRunningInEditor: return

  self.window = self.getWindow()
  self.window.minSize = vector2i(325, 225)
  self.window.maxSize = vector2i(960, 480)

  self.in_node = self/"grid/inbox" as LineEdit
  self.out_node = self/"grid/a/outlabel" as Label

  self.bases = [
    self/"grid/binary_button"  as BaseButton,
    self/"grid/decimal_button" as BaseButton,
    self/"grid/hex_button"     as BaseButton, ]

  print "in signal: " & $self.in_node.connect("text_changed", self.callable "inbox_text_changed")

  let pressed = stringName "pressed"

  print "dec signal: " & $self.bases[Dec].connect(pressed, self.callable "submit_decimal")
  print "bin signal: " & $self.bases[Bin].connect(pressed, self.callable "submit_binary")
  print "hex signal: " & $self.bases[Hex].connect(pressed, self.callable "submit_hex")

  self.output "Hello from Nim-lang!"

proc `$`(state: State): string {.raises: [].} =
  try:
    case state.select
    of Dec:
      let value = state.input.or0.parseInt
      &"""
BIN: {value.myToBin}
HEX: {value.mytoHex}"""
    of Bin:
      let value = state.input.or0.parseBinInt
      &"""
DEC: {value.myToDec}
HEX: {value.myToHex}"""
    of Hex:
      let value = state.input.or0.parseHexInt
      &"""
DEC: {value.myToDec}
BIN: {value.myToBin}"""
  except:
    getCurrentExceptionMsg()

proc inbox_text_changed(self: MainClass; intext: string) {.gdsync.} =
  self.state.input = intext
  self.output $self.state

proc submit_decimal(self: MainClass) {.gdsync.} =
  self.state.select = Dec
  self.output $self.state
proc submit_binary(self: MainClass) {.gdsync.} =
  self.state.select = Bin
  self.output $self.state
proc submit_hex(self: MainClass) {.gdsync.} =
  self.state.select = Hex
  self.output $self.state
```

**Comment by insomniacUNDERSCORElemon** [comment]
> so I tried writing one myself, but it turned out to be something completely

Nice. I see what you mean. A lot cleaner but yeah, more advanced and a different approach with how the GUI is handled (yours should use radiobuttons, though that might make the `state` usage a bit unneeded) and some of the mess in mine was using alternate solutions (like the manual converters, which was the original idea). The separate file (not tied to Godot) was nice when updating, though I suppose that may be a tradeoff.

Also comparing the 2 versions made me see that in mine there's an inaccuracy with the live bin-to-dec live convert where the restriction isn't needed (+message is wrong). I swear it *was* at some point a needed restriction, given that it has been 3 years since the original perhaps parseBinInt (and co) was improved to the limitation that my manual calculation has (which is std/math's `^` because `high(int)`). When I did the rewrite I forgot to add the limit for live hex calculation and didn't notice that it's working just fine.

I think it'd be a good idea for you to add your version (maybe with a name like `main_class_alternate_by_panno8M.nim` or something), wherever you think is best. I would say put it in the `readme` folder and point it out in the extras section of the `.md` file with 

`- An alternate main class by panno8M in README folder`.

Or something like that.

**Pull request merged**
